// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"backend/backend/phase_two/task_four/internal/app"
	"backend/backend/phase_two/task_four/internal/domain/service"
	"backend/backend/phase_two/task_four/internal/infrastructure/persistence"
	"backend/backend/phase_two/task_four/internal/interfaces/http/controller"
	"backend/backend/phase_two/task_four/internal/interfaces/http/routes"
)

import (
	_ "backend/backend/phase_two/task_four/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db, err := NewDB()
	if err != nil {
		return nil, err
	}
	postRepository := persistence.NewGormPostRepository(db)
	postService := service.NewPostService(postRepository)
	postAppService := app.NewPostAppService(postService)
	postController := controller.NewPostController(postAppService)
	postRoutes := routes.NewPostRoutes(postController)
	userRepository := persistence.NewGormUserRepository(db)
	userService := service.NewUserService(userRepository)
	userAppService := app.NewUserAppService(userService)
	userController := controller.NewUserController(userAppService)
	userRoutes := routes.NewUserRoutes(userController)
	loginAppService := app.NewLoginAppService(userService)
	loginController := controller.NewLoginController(loginAppService)
	loginRoutes := routes.NewLoginRoutes(loginController)
	commentRepository := persistence.NewGormCommentRepository(db)
	commentService := service.NewCommentService(commentRepository)
	commentAppService := app.NewCommentAppService(commentService)
	commentController := controller.NewCommentController(commentAppService)
	commentRoutes := routes.NewCommentRoutes(commentController)
	bootstrapApp := NewApp(db, postRoutes, userRoutes, loginRoutes, commentRoutes)
	return bootstrapApp, nil
}
